 
# Copyright 2018 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: python37
# instance_class: F4_1G

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"
  CLOUD_SQL_CONNECTION_NAME: 'tensorflowdeployment:us-central1:coderschool-student'
  DB_USER: "postgres"
  DB_PASS: "Dragonball1"
  DB_NAME: "Student_data"

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /images
  static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto